server:
# 端口
  port: 8443
#  servlet:
#   上下文路径
#    context-path: /api
spring:
  # 导入其他配置文件
  profiles:
    include: util, dao
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  devtools:
#    restart:
#      enabled: true